language: node_js
node_js:
  - "stable"
cache: yarn
install:
  - yarn install
script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: gh-pages