sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t campus-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true campus-frontend npm run test -- --coverage