language: node_js
node_js:
  - "stable"
cache: yarn
install:
  - yarn install
script:
  - yarn test
  - yarn build

branches:
  only:
  - master
  - stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: master