version: "3.7"
services:
  campus-frontend:
    container_name: campus-frontend
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "3010:80"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment: 
      - NODE_ENV=development